### ISSUE TITLE
Migrate to flake

### ISSUE THREAD

**Issue by mnacamura** [mnacamura/etc-nixos#1]
## TODO

- [x] Fix old configs that do not work now (e.g., rofi)
- [x] Move packages that should be installed user-wide to [config-nixpkgs][1]
- [x] ~~Use [colemickens/flake-firefox-nightly][2]~~ use `--impure` option for the moment.
- [ ] #16

## Reference

- [Nix Flakes, Part 3][3]

[1]: https://github.com/mnacamura/config-nixpkgs
[2]: https://github.com/colemickens/flake-firefox-nightly
[3]: https://www.tweag.io/blog/2020-07-31-nixos-flakes/

**Comment by mnacamura** [comment]
Almost done, closing.
